// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEzpD2z_biIkQ0k_d0IcTMqHTCN2q8Dmk',
    appId: '1:380486269565:web:1632e0719972d2d4ef8f14',
    messagingSenderId: '380486269565',
    projectId: 'thunderdoctor-6c47b',
    authDomain: 'thunderdoctor-6c47b.firebaseapp.com',
    storageBucket: 'thunderdoctor-6c47b.firebasestorage.app',
    measurementId: 'G-JSBSZ8KSV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwL0almHcNzZLoNJ2nxhTnkXjTJFEdjf4',
    appId: '1:380486269565:android:90d277e1688deb5def8f14',
    messagingSenderId: '380486269565',
    projectId: 'thunderdoctor-6c47b',
    storageBucket: 'thunderdoctor-6c47b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV0sB6kT7OD90Tg0SoXbN-WHxx4kIqTX0',
    appId: '1:380486269565:ios:39d237213a435d21ef8f14',
    messagingSenderId: '380486269565',
    projectId: 'thunderdoctor-6c47b',
    storageBucket: 'thunderdoctor-6c47b.firebasestorage.app',
    iosClientId: '380486269565-6hkmkhvt7jpcdvv2232rh9hgb8rlmmcr.apps.googleusercontent.com',
    iosBundleId: 'com.example.citas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV0sB6kT7OD90Tg0SoXbN-WHxx4kIqTX0',
    appId: '1:380486269565:ios:39d237213a435d21ef8f14',
    messagingSenderId: '380486269565',
    projectId: 'thunderdoctor-6c47b',
    storageBucket: 'thunderdoctor-6c47b.firebasestorage.app',
    iosClientId: '380486269565-6hkmkhvt7jpcdvv2232rh9hgb8rlmmcr.apps.googleusercontent.com',
    iosBundleId: 'com.example.citas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEzpD2z_biIkQ0k_d0IcTMqHTCN2q8Dmk',
    appId: '1:380486269565:web:aff21f8fae278052ef8f14',
    messagingSenderId: '380486269565',
    projectId: 'thunderdoctor-6c47b',
    authDomain: 'thunderdoctor-6c47b.firebaseapp.com',
    storageBucket: 'thunderdoctor-6c47b.firebasestorage.app',
    measurementId: 'G-ZC36QT1Z81',
  );
}
